config/routes.rb
Versus::Application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      devise_for :users
      resources :games, :only => [:index, :create]
      resources :members, :only => :index do
        collection do
          get 'suggest'
        end
        member do
          post 'play'
        end
      end

      post 'users/register_device_token' => 'users#register_device_token'
    end
  end

  resources :games
  resources :groups
  resources :users, only: :show do
    member do
      get "profile"
    end
  end

  root to: "home#index"
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :winner, foreign_key: :winner_id, class_name: 'User'
  belongs_to :loser,  foreign_key: :loser_id,  class_name: 'User'
end

app/controllers/api/v1/games_controller.rb
module Api::V1
	class GamesController < Controller
		def index
			@games = Game.joins(:winner, :loser)
		end

    def create
      loser_id = game_params[:loser_id]
      if current_user.id == loser_id.to_i
        render status: :forbidden, :json => { errors: 'You just tried to register a win against yourself. You\'re not too bright, are you?' }
        return
      end
      if Game.where(winner_id: current_user.id, loser_id: loser_id).where("created_at > ?", Time.now - 5.minutes).exists?
        render status: :forbidden, :json => { errors: 'You just posted a win against this player. Chill!' }
        return
      end
      @game = Game.new({
        loser_id:  loser_id,
        winner: current_user
      })
      
      if @game.save
        render :status => 200, :json => { :success => true }
      else
        render json: @game.errors, status: :unprocessable_entity
      end
    end

    private

      def game_params
        params.require(:game).permit(:winner_id, :loser_id)
      end

	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
    authorize! :read, @games
  end

  # GET /games/1
  # GET /games/1.json
  def show
    authorize! :read, @game
  end

  # GET /games/new
  def new
    @game = Game.new
    @opponents = current_user.opponents
    authorize! :create, @game
  end

  # GET /games/1/edit
  def edit
    authorize! :update, @game
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new({
      loser:  User.find(game_params[:loser_id]),
      winner: current_user
    })
    authorize! :create, @game
    respond_to do |format|
      if @game.save
        format.html { redirect_to profile_user_path(current_user), notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    authorize! :update, @game
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    authorize! :destroy, @game
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:winner_id, :loser_id)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <div class="i-beat">
    <h1>I Beat <%= collection_select(:game, :loser_id, @opponents, :id, :email, {}, class: 'form-control') %> </h1>


  <%= f.submit "Make it known", class: "btn btn-success btn-lg" %>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Winner</th>
      <th>Loser</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.winner_id %></td>
        <td><%= game.loser_id %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<%= render 'form' %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Winner:</strong>
  <%= @game.winner_id %>
</p>

<p>
  <strong>Loser:</strong>
  <%= @game.loser_id %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>